### PR TITLE
feature: bundle fbms

### PR DESCRIPTION
**Pull request by ChristianMurphy**
##### Checklist

-   [x] the [individual contributor license agreement][] is signed
-   [x] commit message follows [commit guidelines][]

##### Description of change

include the form builder microservice as a overlay in uPortal start by default.

[individual contributor license agreement]: https://github.com/Jasig/uPortal/blob/master/.github/CONTRIBUTING.md#individual-contributor-license-agreement
[commit guidelines]: https://github.com/Jasig/uPortal/blob/master/.github/CONTRIBUTING.md#commit
[message properties]: https://github.com/Jasig/uPortal/tree/master/uportal-war/src/main/resources/properties/i18n
[WCAG 2.0 AA]: https://www.w3.org/WAI/WCAG20/quickref/?levels=aaa&technologies=smil%2Cpdf%2Cflash%2Csl

### CODE REVIEW

**Comment by ChristianMurphy** [comment]
This is erroring with

```
[ant:java] 2018-10-04 00:16:34.383 ERROR 8461 --- [           main] com.zaxxer.hikari.pool.HikariPool        : HikariPool-1 - Exception during pool initialization.
[ant:java] 
[ant:java] java.sql.SQLTransientConnectionException: java.net.ConnectException: Connection refused (Connection refused)
[ant:java] 	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source) ~[hsqldb-2.4.1.jar:2.4.1]
[ant:java] 	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source) ~[hsqldb-2.4.1.jar:2.4.1]
[ant:java] 	at org.hsqldb.jdbc.JDBCConnection.<init>(Unknown Source) ~[hsqldb-2.4.1.jar:2.4.1]
[ant:java] 	at org.hsqldb.jdbc.JDBCDriver$1.run(Unknown Source) ~[hsqldb-2.4.1.jar:2.4.1]
[ant:java] Caused by: org.hsqldb.HsqlException: java.net.ConnectException: Connection refused (Connection refused)
[ant:java] 	at org.hsqldb.ClientConnection.openConnection(Unknown Source) ~[hsqldb-2.4.1.jar:2.4.1]
[ant:java] 	at org.hsqldb.ClientConnection.initConnection(Unknown Source) ~[hsqldb-2.4.1.jar:2.4.1]
[ant:java] 	at org.hsqldb.ClientConnection.<init>(Unknown Source) ~[hsqldb-2.4.1.jar:2.4.1]
[ant:java] 	... 2 common frames omitted
[ant:java] Caused by: java.net.ConnectException: Connection refused (Connection refused)
[ant:java] 	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_151]
[ant:java] 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_151]
[ant:java] 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_151]
[ant:java] 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_151]
[ant:java] 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_151]
[ant:java] 	at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_151]
[ant:java] 	at java.net.Socket.connect(Socket.java:538) ~[na:1.8.0_151]
[ant:java] 	at java.net.Socket.<init>(Socket.java:434) ~[na:1.8.0_151]
[ant:java] 	at java.net.Socket.<init>(Socket.java:211) ~[na:1.8.0_151]
[ant:java] 	at org.hsqldb.server.HsqlSocketFactory.createSocket(Unknown Source) ~[hsqldb-2.4.1.jar:2.4.1]
[ant:java] 	... 5 common frames omitted
[ant:java] 
[ant:java] 2018-10-04 00:16:34.385  WARN 8461 --- [           main] o.h.engine.jdbc.spi.SqlExceptionHelper   : SQL Error: -1301, SQLState: 08001
[ant:java] 2018-10-04 00:16:34.385 ERROR 8461 --- [           main] o.h.engine.jdbc.spi.SqlExceptionHelper   : java.net.ConnectException: Connection refused (Connection refused)
[ant:java] 2018-10-04 00:16:34.386  WARN 8461 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is javax.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate SessionFactory; nested exception is org.hibernate.exception.JDBCConnectionException: Unable to open JDBC Connection for DDL execution
[ant:java] 2018-10-04 00:16:34.390  INFO 8461 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
[ant:java] 2018-10-04 00:16:34.435  INFO 8461 --- [           main] ConditionEvaluationReportLoggingListener : 
[ant:java] 
[ant:java] Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
[ant:java] 2018-10-04 00:16:34.439 ERROR 8461 --- [           main] o.s.boot.SpringApplication               : Application run failed
```

on MariaDB

**Comment by ChristianMurphy** [comment]
@jgribonvald any ideas on why MariaDB is refusing connections? :thought_balloon:

**Comment by jgribonvald** [comment]
mhhh, in my mind it's due to hibernate version 5 from fbms. Maybe there is a conflict as the dependencies use the portal db's one, so hibernate version 4.x...
Also for this case it will be needed to use a provided dialect for this hibernate version. But I don't know which one between:  MariaDB10Dialect (extends as default MariaDB dialect with INNODB), or the MysqlInnoDBDialect.
Also with mysql lib it seems that we don't need anymore to set this kind on dialect as it can be setted from JVM args likes it indicated : `@deprecated Use "hibernate.dialect.storage_engine=innodb" environment variable or JVM system property instead`

**Comment by jgribonvald** [comment]
I didn't get the time to test, but in my mind you should include the mysql lib into the project and define the specific dialect, here is what I've made to be able to deploy on mariaDB : https://github.com/Jasig/uPortal-start/pull/149/files#diff-354f30a63fb0907d4ad57269548329e3R131

**Comment by jgribonvald** [comment]
Ok after watching I'm sure this is working with HSQLby change :laughing:  is because you have the exact same conf into fbms application.properties

**Comment by drewwills** [comment]
@jgribonvald -- yes... https://github.com/uPortal-contrib/fbms/issues/10

**Comment by ChristianMurphy** [comment]
This has stalled and is outdated.
Closing it out for now, hopefully it can be revisited in a future PR.

**Pull request closed without merging**
